defaults:
  - config  # Refers to 'config.yaml' inside 'mdlm/configs'
  - _self_

eval:
  checkpoint_path: 'kuleshov-group/mdlm-owt'

backbone: 'hf_dit'

loader: 
  eval_batch_size: 8

model:
  length: 100

smc:
  remdm:
    schedule: "cosine"
    remask_strategy: "rescale"
    eta: 0.00
  resampling:
    ess_threshold: 0.5
    partial: False
    frequency: 10
  phi: 4
  tau: 1.0
  kl_weight: 0.2
  num_inference_steps: 100
  num_particles: 8
  batch_p: 8
  lambda_tempering:
    enabled: True
    one_at: 100
  proposal_type: "locally_optimal"
  use_continuous_formulation: True
  prompt_text: null # Specify at run time
