hydra:
  searchpath:
    - file://mdlm/configs
  run:
    dir: ./outputs/${smc.proposal_type}_${smc.num_particles}_${smc.kl_weight}_${smc.resampling.frequency}_${smc.phi}/${now:%Y.%m.%d}/${now:%H%M%S}
  job:
    chdir: true

defaults:
  - base
  - _self_
